"""create alarms table

Revision ID: 6e482063878e
Revises:
Create Date: 2026-04-03 21:21:43.156058

"""

import sqlmodel
from typing import Union
from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "6e482063878e"
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "alarms",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("label", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("status", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("alarm_type", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("series_id", sa.Uuid(), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("schedule_hour", sa.Integer(), nullable=False),
        sa.Column("schedule_minute", sa.Integer(), nullable=False),
        sa.Column(
            "schedule_recurrence", sqlmodel.sql.sqltypes.AutoString(), nullable=True
        ),
        sa.Column(
            "intro_audio_file", sqlmodel.sql.sqltypes.AutoString(), nullable=False
        ),
        sa.Column(
            "sunrise_room_name", sqlmodel.sql.sqltypes.AutoString(), nullable=False
        ),
        sa.Column(
            "sunrise_scene_name", sqlmodel.sql.sqltypes.AutoString(), nullable=False
        ),
        sa.Column("sunrise_duration_minutes", sa.Integer(), nullable=False),
        sa.Column("sunrise_brightness_start", sa.Integer(), nullable=False),
        sa.Column("sunrise_brightness_end", sa.Integer(), nullable=False),
        sa.Column("sunrise_steps", sa.Integer(), nullable=False),
        sa.Column(
            "ringtone_audio_file", sqlmodel.sql.sqltypes.AutoString(), nullable=False
        ),
        sa.Column("ringtone_volume", sa.Integer(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("alarms")
    # ### end Alembic commands ###
